nodeLinker: node-modules

packageExtensions:
  "@firebase/auth@*":
    dependencies:
      "@firebase/app-types": "*"
      "@firebase/util": "*"
  "@firebase/database@*":
    peerDependencies:
      "@firebase/app": "*"
      "@firebase/app-types": "*"
  "@material-ui/data-grid@*":
    dependencies:
      "@material-ui/styles": "*"
      react-dom: "*"
  raw-loader@*:
    dependencies:
      webpack: "*"
  react-dev-utils@*:
    dependencies:
      typescript: "*"
      webpack: "*"
  react-draft-wysiwyg@*:
    dependencies:
      immutable: "*"
  react-frame-component@*:
    dependencies:
      prop-types: "*"
  react-redux@*:
    dependencies:
      react-dom: "*"
  react-router-config@*:
    dependencies:
      react-router: "*"
  react-swipeable-views-utils@*:
    peerDependencies:
      react: "*"
  react-table@*:
    dependencies:
      prop-types: "*"
  styled-components@*:
    dependencies:
      react-is: "*"
